name: Publish Helm Chart

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Update chart version
        run: |
          VERSION=$(cat VERSION)
          make update-helm-chart VERSION=$VERSION

      - name: Fetch gh-pages index.yaml
        run: |
          git fetch origin gh-pages
          mkdir -p dist/chart
          git show origin/gh-pages:index.yaml > dist/chart/index.yaml || true

      - name: Package Helm chart
        run: |
          cd dist/chart
          VERSION=$(cat ../../VERSION)
          helm package . --version $VERSION --app-version $VERSION
          helm repo index . --url https://upbothq.github.io/upbot-operator/ --merge index.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./dist/chart
          publish_branch: gh-pages
