name: Version Bump

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Type of version bump'
        required: true
        type: choice
        options:
          - patch
          - minor  
          - major
        default: patch
      commit_message:
        description: 'Custom commit message (optional)'
        required: false
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(cat VERSION)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump_version
        run: |
          make version-bump-${{ github.event.inputs.bump_type }}
          NEW_VERSION=$(cat VERSION)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update Helm chart
        run: |
          make update-helm-chart

      - name: Commit changes
        run: |
          git add VERSION dist/chart/Chart.yaml
          if [[ -n "${{ github.event.inputs.commit_message }}" ]]; then
            COMMIT_MSG="${{ github.event.inputs.commit_message }}"
          else
            COMMIT_MSG="chore: bump version from ${{ steps.current_version.outputs.CURRENT_VERSION }} to ${{ steps.bump_version.outputs.NEW_VERSION }}"
          fi
          git commit -m "$COMMIT_MSG"
          git push

      - name: Generate summary
        run: |
          echo "## Version Bump Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Bump Type:** ${{ github.event.inputs.bump_type }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Previous Version:** ${{ steps.current_version.outputs.CURRENT_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **New Version:** ${{ steps.bump_version.outputs.NEW_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Files Updated:** VERSION, dist/chart/Chart.yaml" >> $GITHUB_STEP_SUMMARY